# Generated by Django 6.1.1 on 2026-09-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock_type',
            field=models.CharField(choices=[('fabric', 'Tissu'), ('accessory', 'Accessoire / mercerie'), ('other', 'Autre')], default='fabric', max_length=16),
        ),
    ]
