# Generated by Django 6.1.1 on 2026-09-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('metrics', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='reporting_r_period__cdeae6_idx')],
            },
        ),
    ]
