# Generated by Django 6.1.1 on 2026-09-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('role_title', models.CharField(blank=True, default='', max_length=255)),
                ('monthly_salary_fcfa', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='staff.employee')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('done', 'Terminé')], default='pending', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='staff.employee')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='staff_emplo_name_1f9ec4_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffperformance',
            constraint=models.UniqueConstraint(fields=('employee', 'period_year', 'period_month'), name='staff_perf_period_unique'),
        ),
    ]
