# Generated by Django 6.1.1 on 2026-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
