# Generated by Django 6.1.1 on 2026-09-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('fields', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('reference_price_fcfa', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('validated', 'Validé'), ('delivered', 'Livré')], default='pending', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_fcfa', models.BigIntegerField(default=0)),
                ('advance_payment_fcfa', models.BigIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire')], default='', max_length=32)),
                ('delivery_mode', models.CharField(choices=[('pickup', 'Retrait en boutique'), ('delivery', 'Livraison')], default='pickup', max_length=24)),
                ('discount_scope', models.CharField(choices=[('none', 'Aucune'), ('all', 'Toute la commande'), ('line', 'Par article')], default='none', max_length=8)),
                ('order_discount_fcfa', models.BigIntegerField(default=0)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('model_notes', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('inventory_deducted_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='staff.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
                ('measurement_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.measurementformtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, default='', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_assignments', to='staff.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='orders/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_characteristic_key', models.CharField(blank=True, default='', max_length=64)),
                ('inventory_consumed_meters', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_fcfa', models.BigIntegerField(default=0)),
                ('discount_fcfa', models.BigIntegerField(default=0)),
                ('discount_applies', models.BooleanField(default=False)),
                ('client_supplies_fabric', models.BooleanField(default=False)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory.inventoryitem')),
                ('measurement_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.measurementformtemplate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('validated', 'Validé'), ('delivered', 'Livré')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
