# Generated by Django 6.1.1 on 2026-09-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('balance_fcfa', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Défaut', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('poitrine_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('taille_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hanche_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('longueur_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('epaule_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('custom_measures', models.JSONField(blank=True, default=list)),
                ('measurement_notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
